### ISSUE TITLE
Differences with owlcarousel2-a11ylayer

### ISSUE THREAD

**Issue by lbineau** [stephan-fischer/owl-aria#1]
Hello @stephan-fischer,

Not an issue but more a question, what are the difference between https://github.com/rtrvrtg/owlcarousel2-a11ylayer and yours?
I'm trying to pick one.

Regards.

**Comment by jwwicks** [comment]
@lbineau ,
Functionally there isn't a difference. This one has a more modern code arrangement.

**Comment by stephan-fischer** [comment]
The problem was to work with nested carousels. This plugin solves issues with the a11ylayer.
